# Generated by Django 4.2.6 on 2023-12-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_imageuploadform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_cashier',
            new_name='is_regularuser',
        ),
        migrations.AddField(
            model_name='user',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
