# Generated by Django 4.2.6 on 2023-12-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_rename_is_cashier_user_is_regularuser_user_is_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=20)),
                ('device_model', models.CharField(max_length=100)),
                ('current_version', models.CharField(max_length=20)),
                ('firmware_file', models.FileField(upload_to='firmwares/')),
            ],
        ),
    ]
