# Generated by Django 5.0 on 2023-12-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_firmware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmware',
            name='firmware_file',
            field=models.FileField(blank=True, null=True, upload_to='firmwares/'),
        ),
    ]
