# Generated by Django 5.0.2 on 2024-04-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_alter_firmware_firmware_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('firmware_version', models.CharField(max_length=100)),
                ('source_url', models.URLField()),
                ('download_link', models.URLField()),
            ],
        ),
    ]
