# Generated by Django 5.0.2 on 2024-04-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_scrapeddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='tenda_download_link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
