# Generated by Django 5.0.2 on 2024-04-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_scrapeddata_tenda_download_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='download_link',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='tenda_download_link',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
