# Generated by Django 5.0.2 on 2024-04-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_alter_scrapeddata_download_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='download_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='tenda_download_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
