# Generated by Django 5.0.2 on 2024-04-23 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_alter_scrapeddata_download_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmware',
            name='version',
        ),
    ]
