# Generated by Django 5.0.2 on 2024-04-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0015_remove_firmware_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('firmware_version', models.CharField(max_length=100)),
                ('source_url', models.URLField()),
                ('download_link', models.CharField(blank=True, max_length=255, null=True)),
                ('tenda_download_link', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
