# Generated by Django 5.0.2 on 2024-04-23 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_searchdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchdata',
            old_name='download_link',
            new_name='Download_link',
        ),
        migrations.RenameField(
            model_name='searchdata',
            old_name='firmware_version',
            new_name='Firmware_version',
        ),
        migrations.RenameField(
            model_name='searchdata',
            old_name='model_name',
            new_name='Model_name',
        ),
        migrations.RenameField(
            model_name='searchdata',
            old_name='source_url',
            new_name='Source_url',
        ),
        migrations.RenameField(
            model_name='searchdata',
            old_name='tenda_download_link',
            new_name='Tenda_download_link',
        ),
    ]
